### PR TITLE
Adds Dockerfile and Apronfile

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
https://jira.blueapron.com/browse/DEV-1775

### CODE REVIEW

**Comment by edgar** [comment]
Looks good, we gonna need to do some tasks in conjunction with DevOps before migrating this from heroku to AWS.
Unfortunately the domain currently in use is: `http://wms-bwip.herokuapp.com/`
So, we gonna need to create a new domain, and adjust the new app to respond to both domains.
Then deploy the change in the [front-end app](https://github.com/blueapron/wms-outbound/blob/8d628c611e6b0db160e3c093d3c039f54b7d55a8/app/components/data-matrix.js#L25) to use the new domain.

**Comment by michaeldauria** [comment]
We can't split the DNS on `herokuapp.com` so it will have to be a hard cut over to `bwip-js.<env>.b--a.co`

**Comment by edgar** [comment]
What about a `redirect` from new domain to the old one?

**Comment by edgar** [comment]
@michaeldauria it seems like currently we have heroku apps responding to `herokuapp.com` and `blueapron.com`, for instance:

https://ba-wms-staging-2.herokuapp.com

https://wms-staging-2.blueapron.com

**Comment by TheDudeWithTheThing** [comment]
@edgar we should be ok once this is up for a while. Any idea how long it takes for all BTT devices to be refreshed?

1. Get this up
2. Make url change in BTT ( are there other tools too? )
3. Check in like a month if anything is still hitting the heroku one, if not we can kill it.

**Comment by edgar** [comment]
💯 

(just BTT in outbound uses it)

**Pull request merged**
